# 讀取檔案

In [1]:
import numpy as np
import os


# 檔案路徑
file_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_random_20250822\random_choose_loc_id_10_set_2.npy"

# 讀取 .npy 檔案
data = np.load(file_path, allow_pickle=True)

# 顯示資料型態與內容
print("資料型態:", type(data))
print("資料形狀:", getattr(data, 'shape', '無 shape 屬性'))
print("內容預覽:\n", data)


資料型態: <class 'numpy.ndarray'>
資料形狀: (10, 10)
內容預覽:
 [[25608. 39836. 20525. 85232. 13493. 60136. 45323. 13493. 48934. 60679.]
 [78732. 66905. 75238. 13751. 63831. 92353. 58723.  9881. 45925. 43677.]
 [97210. 85232. 78066.  1023. 88531. 65175. 94124. 60566. 31624. 55440.]
 [91913. 93867.  8560. 75238. 94705. 65961. 95495. 64972. 67572. 91880.]
 [57178.  7807.  6658. 73699. 51359. 44129. 76077. 50478.  3034. 75119.]
 [23763. 59169.  4440. 95563. 26271. 54226. 21896. 67235. 72024. 77943.]
 [54911.  8715. 73277. 54210. 89050. 84050. 59284. 12980. 82278. 42485.]
 [37155. 93638. 57077. 45350. 16066. 30959. 70431. 20273. 66153. 60701.]
 [59602.  5542.  6375. 99510. 46338. 23729. 31864. 72065.  2821. 14960.]
 [54983. 26034. 38222. 11860. 21727. 22741. 80478. 10516. 17800. 31459.]]


# random 之資料計算

In [7]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_random_20250822"

# 不同的 coverage 值
coverages = [5, 10, 20, 40, 60, 80, 100]

# 儲存結果
results = {}

print("=" * 60)
for coverage in coverages:
    # 建立檔案名稱
    file_name = f"random_choose_coverage_{coverage}_set_10.npy"
    file_path = os.path.join(base_path, file_name)
    
    # 檢查檔案是否存在
    if os.path.exists(file_path):
        # 讀取資料
        data = np.load(file_path, allow_pickle=True)
        
        # 計算平均值
        mean_value = np.mean(data)
        
        # 儲存結果
        results[coverage] = mean_value
        
        print(f"Coverage {coverage:3d}: 平均值 = {mean_value:.6f}")
        print(f"  - 資料形狀: {data.shape}")
        print(f"  - 資料範圍: [{np.min(data):.6f}, {np.max(data):.6f}]")
        print("-" * 60)
    else:
        print(f"Coverage {coverage:3d}: 檔案不存在！")
        print(f"  - 路徑: {file_path}")
        print("-" * 60)

print("=" * 60)
print("\n摘要:")
print(f"{'Coverage':<12} {'平均值':<15}")
print("-" * 27)
for coverage, mean_val in results.items():
    print(f"{coverage:<12} {mean_val:<15.6f}")

Coverage   5: 平均值 = 99.170000
  - 資料形狀: (10, 10)
  - 資料範圍: [48.000000, 155.000000]
------------------------------------------------------------
Coverage  10: 平均值 = 192.730000
  - 資料形狀: (10, 10)
  - 資料範圍: [97.000000, 267.000000]
------------------------------------------------------------
Coverage  20: 平均值 = 366.400000
  - 資料形狀: (10, 10)
  - 資料範圍: [264.000000, 508.000000]
------------------------------------------------------------
Coverage  40: 平均值 = 628.360000
  - 資料形狀: (10, 10)
  - 資料範圍: [478.000000, 748.000000]
------------------------------------------------------------
Coverage  60: 平均值 = 826.870000
  - 資料形狀: (10, 10)
  - 資料範圍: [661.000000, 922.000000]
------------------------------------------------------------
Coverage  80: 平均值 = 972.050000
  - 資料形狀: (10, 10)
  - 資料範圍: [826.000000, 1093.000000]
------------------------------------------------------------
Coverage 100: 平均值 = 1088.630000
  - 資料形狀: (10, 10)
  - 資料範圍: [931.000000, 1185.000000]
---------------------------------------

# PIO 之資料計算

In [9]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap"

# 不同的 coverage 和 dmin 值
coverages = [5, 10, 20, 40, 60, 80, 100]
dmin_values = [0.6, 0.8, 0.96, 1, 1.2]

# 儲存結果
results = {}

print("=" * 80)
print("開始分析檔案...")
print("=" * 80)

for coverage in coverages:
    results[coverage] = {}
    
    for dmin in dmin_values:
        # 建立檔案名稱 (修正: 使用 coverage 和 dmin 的具體值)
        file_name = f"deployment_decision_coverage_{coverage}_set_10_dist_{dmin}.npy"
        file_path = os.path.join(base_path, file_name)
        
        # 檢查檔案是否存在
        if os.path.exists(file_path):
            try:
                # 讀取資料
                data = np.load(file_path, allow_pickle=True)
                
                # 計算平均值
                mean_value = np.mean(data)
                
                # 儲存結果
                results[coverage][dmin] = {
                    'mean': mean_value,
                    'shape': data.shape,
                    'min': np.min(data),
                    'max': np.max(data),
                    'std': np.std(data)
                }
                
                print(f"✓ Coverage {coverage:3d}, Dmin {dmin:.2f}:")
                print(f"    平均值 = {mean_value:.6f}, 標準差 = {np.std(data):.6f}")
                print(f"    形狀 = {data.shape}, 範圍 = [{np.min(data):.6f}, {np.max(data):.6f}]")
                
            except Exception as e:
                print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 讀取錯誤 - {e}")
                results[coverage][dmin] = None
        else:
            print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 檔案不存在")
            results[coverage][dmin] = None
    
    print("-" * 80)

print("=" * 80)
print("\n摘要表格:")
print("=" * 80)

# 建立表格標題
header = f"{'N':<12}"
for dmin in dmin_values:
    header += f"{'Dmin=' + str(dmin):<15}"
print(header)
print("-" * (12 + 15 * len(dmin_values)))

# 輸出表格內容
for coverage in coverages:
    row = f"{coverage:<12}"
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            row += f"{results[coverage][dmin]['mean']:<15.6f}"
        else:
            row += f"{'N/A':<15}"
    print(row)

print("=" * 80)

# 額外統計: 找出最佳組合
print("\n最佳組合 (最大平均值):")
max_mean = -np.inf
best_coverage = None
best_dmin = None

for coverage in coverages:
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            current_mean = results[coverage][dmin]['mean']
            if current_mean > max_mean:
                max_mean = current_mean
                best_coverage = coverage
                best_dmin = dmin

if best_coverage is not None:
    print(f"Coverage = {best_coverage}, Dmin = {best_dmin}, 平均值 = {max_mean:.6f}")
else:
    print("未找到有效數據")

開始分析檔案...
✓ Coverage   5, Dmin 0.60:
    平均值 = 163.100000, 標準差 = 5.557877
    形狀 = (10,), 範圍 = [152.000000, 173.000000]
✓ Coverage   5, Dmin 0.80:
    平均值 = 163.100000, 標準差 = 5.557877
    形狀 = (10,), 範圍 = [152.000000, 173.000000]
✓ Coverage   5, Dmin 0.96:
    平均值 = 163.100000, 標準差 = 5.557877
    形狀 = (10,), 範圍 = [152.000000, 173.000000]
✓ Coverage   5, Dmin 1.00:
    平均值 = 163.100000, 標準差 = 5.557877
    形狀 = (10,), 範圍 = [152.000000, 173.000000]
✓ Coverage   5, Dmin 1.20:
    平均值 = 163.100000, 標準差 = 5.557877
    形狀 = (10,), 範圍 = [152.000000, 173.000000]
--------------------------------------------------------------------------------
✓ Coverage  10, Dmin 0.60:
    平均值 = 293.400000, 標準差 = 14.374978
    形狀 = (10,), 範圍 = [264.000000, 309.000000]
✓ Coverage  10, Dmin 0.80:
    平均值 = 294.000000, 標準差 = 13.213629
    形狀 = (10,), 範圍 = [270.000000, 309.000000]
✓ Coverage  10, Dmin 0.96:
    平均值 = 294.000000, 標準差 = 13.213629
    形狀 = (10,), 範圍 = [270.000000, 309.000000]
✓ Coverage  10, Dmin 1.00:

# PO

In [10]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp"

# 不同的 coverage 和 dmin 值
coverages = [5, 10, 20, 40, 60, 80, 100]
dmin_values = [0.6, 0.8, 0.96, 1, 1.2]

# 儲存結果
results = {}

print("=" * 80)
print("開始分析檔案...")
print("=" * 80)

for coverage in coverages:
    results[coverage] = {}
    
    for dmin in dmin_values:
        # 建立檔案名稱 (修正: 使用 coverage 和 dmin 的具體值)
        file_name = f"deployment_decision_coverage_{coverage}_set_10_dist_{dmin}.npy"
        file_path = os.path.join(base_path, file_name)
        
        # 檢查檔案是否存在
        if os.path.exists(file_path):
            try:
                # 讀取資料
                data = np.load(file_path, allow_pickle=True)
                
                # 計算平均值
                mean_value = np.mean(data)
                
                # 儲存結果
                results[coverage][dmin] = {
                    'mean': mean_value,
                    'shape': data.shape,
                    'min': np.min(data),
                    'max': np.max(data),
                    'std': np.std(data)
                }
                
                print(f"✓ Coverage {coverage:3d}, Dmin {dmin:.2f}:")
                print(f"    平均值 = {mean_value:.6f}, 標準差 = {np.std(data):.6f}")
                print(f"    形狀 = {data.shape}, 範圍 = [{np.min(data):.6f}, {np.max(data):.6f}]")
                
            except Exception as e:
                print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 讀取錯誤 - {e}")
                results[coverage][dmin] = None
        else:
            print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 檔案不存在")
            results[coverage][dmin] = None
    
    print("-" * 80)

print("=" * 80)
print("\n摘要表格:")
print("=" * 80)

# 建立表格標題
header = f"{'N':<12}"
for dmin in dmin_values:
    header += f"{'Dmin=' + str(dmin):<15}"
print(header)
print("-" * (12 + 15 * len(dmin_values)))

# 輸出表格內容
for coverage in coverages:
    row = f"{coverage:<12}"
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            row += f"{results[coverage][dmin]['mean']:<15.6f}"
        else:
            row += f"{'N/A':<15}"
    print(row)

print("=" * 80)

# 額外統計: 找出最佳組合
print("\n最佳組合 (最大平均值):")
max_mean = -np.inf
best_coverage = None
best_dmin = None

for coverage in coverages:
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            current_mean = results[coverage][dmin]['mean']
            if current_mean > max_mean:
                max_mean = current_mean
                best_coverage = coverage
                best_dmin = dmin

if best_coverage is not None:
    print(f"Coverage = {best_coverage}, Dmin = {best_dmin}, 平均值 = {max_mean:.6f}")
else:
    print("未找到有效數據")

開始分析檔案...
✓ Coverage   5, Dmin 0.60:
    平均值 = 126.600000, 標準差 = 5.388877
    形狀 = (10,), 範圍 = [116.000000, 132.000000]
✓ Coverage   5, Dmin 0.80:
    平均值 = 129.800000, 標準差 = 5.287722
    形狀 = (10,), 範圍 = [116.000000, 138.000000]
✓ Coverage   5, Dmin 0.96:
    平均值 = 140.500000, 標準差 = 5.920304
    形狀 = (10,), 範圍 = [132.000000, 150.000000]
✓ Coverage   5, Dmin 1.00:
    平均值 = 142.200000, 標準差 = 6.095900
    形狀 = (10,), 範圍 = [135.000000, 151.000000]
✓ Coverage   5, Dmin 1.20:
    平均值 = 153.000000, 標準差 = 7.771744
    形狀 = (10,), 範圍 = [139.000000, 165.000000]
--------------------------------------------------------------------------------
✓ Coverage  10, Dmin 0.60:
    平均值 = 175.600000, 標準差 = 6.887670
    形狀 = (10,), 範圍 = [164.000000, 186.000000]
✓ Coverage  10, Dmin 0.80:
    平均值 = 217.000000, 標準差 = 11.899580
    形狀 = (10,), 範圍 = [199.000000, 233.000000]
✓ Coverage  10, Dmin 0.96:
    平均值 = 236.000000, 標準差 = 10.039920
    形狀 = (10,), 範圍 = [216.000000, 253.000000]
✓ Coverage  10, Dmin 1.00:


# coverage

In [91]:
import numpy as np
import os
import csv

# 不同的 N 值和 dist 值
N_values = [5, 10, 20, 40, 60, 80, 100]
dist_values = [0.6, 0.8, 0.96, 1, 1.2]

# 基礎路徑
base_path_nn_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_nn_20250415\mlp"
base_path_xgb_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp"


# 輸出 CSV
output_csv = "matrix_PO_cov.csv"

# 建立矩陣，第一列是表頭
matrix = [["N值 \\ dist值"] + dist_values]

for N in N_values:
    row = [N]
    for dist in dist_values:
        file_template = f"deployment_decision_coverage_{N}_set_10_dist_{dist}.npy"
        
        try:
            data_nn = np.load(os.path.join(base_path_nn_shap, file_template), allow_pickle=True)
            avg_nn = np.mean(data_nn)
        except:
            avg_nn = None
        
        try:
            data_xgb = np.load(os.path.join(base_path_xgb_shap, file_template), allow_pickle=True)
            avg_xgb = np.mean(data_xgb)
        except:
            avg_xgb = None
        
        if avg_nn is not None and avg_xgb is not None:
            rel_diff = ((avg_xgb - avg_nn) / avg_nn) * 100
            row.append(f"{rel_diff:+.2f}%")
        else:
            row.append("缺少數據")
    
    matrix.append(row)

# 存成 CSV
with open(output_csv, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerows(matrix)

print(f"\n✅ 已輸出 7×5 的矩陣表到 {output_csv}")



✅ 已輸出 7×5 的矩陣表到 matrix_PO_cov.csv


In [92]:
import numpy as np
import os
import csv

# 不同的 N 值和 dist 值
N_values = [5, 10, 20, 40, 60, 80, 100]
dist_values = [0.6, 0.8, 0.96, 1, 1.2]

# 基礎路徑
base_path_nn_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_nn_20250415\shap"
base_path_xgb_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap"


# 輸出 CSV
output_csv = "matrix_PIO_cov.csv"

# 建立矩陣，第一列是表頭
matrix = [["N值 \\ dist值"] + dist_values]

for N in N_values:
    row = [N]
    for dist in dist_values:
        file_template = f"deployment_decision_coverage_{N}_set_10_dist_{dist}.npy"
        
        try:
            data_nn = np.load(os.path.join(base_path_nn_shap, file_template), allow_pickle=True)
            avg_nn = np.mean(data_nn)
        except:
            avg_nn = None
        
        try:
            data_xgb = np.load(os.path.join(base_path_xgb_shap, file_template), allow_pickle=True)
            avg_xgb = np.mean(data_xgb)
        except:
            avg_xgb = None
        
        if avg_nn is not None and avg_xgb is not None:
            rel_diff = ((avg_xgb - avg_nn) / avg_nn) * 100
            row.append(f"{rel_diff:+.2f}%")
        else:
            row.append("缺少數據")
    
    matrix.append(row)

# 存成 CSV
with open(output_csv, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerows(matrix)

print(f"\n✅ 已輸出 7×5 的矩陣表到 {output_csv}")



✅ 已輸出 7×5 的矩陣表到 matrix_PIO_cov.csv


# suvival rate

In [93]:
import numpy as np
import os
import csv

# 不同的 N 值和 dist 值
N_values = [5, 10, 20, 40, 60, 80, 100]
dist_values = [0.6, 0.8, 0.96, 1, 1.2]

# 基礎路徑
base_path_nn_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_nn_20250415\mlp"
base_path_xgb_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp"


# 輸出 CSV
output_csv = "matrix_PO_sur.csv"

# 建立矩陣，第一列是表頭
matrix = [["N值 \\ dist值"] + dist_values]

for N in N_values:
    row = [N]
    for dist in dist_values:
        file_template = f"deploy_decision_survivalrate_average_{N}_set_10_dist_{dist}.npy"
        
        try:
            data_nn = np.load(os.path.join(base_path_nn_shap, file_template), allow_pickle=True)
            avg_nn = np.mean(data_nn)
        except:
            avg_nn = None
        
        try:
            data_xgb = np.load(os.path.join(base_path_xgb_shap, file_template), allow_pickle=True)
            avg_xgb = np.mean(data_xgb)
        except:
            avg_xgb = None
        
        if avg_nn is not None and avg_xgb is not None:
            rel_diff = ((avg_xgb - avg_nn) / avg_nn) * 100
            row.append(f"{rel_diff:+.2f}%")
        else:
            row.append("缺少數據")
    
    matrix.append(row)

# 存成 CSV
with open(output_csv, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerows(matrix)

print(f"\n✅ 已輸出 7×5 的矩陣表到 {output_csv}")



✅ 已輸出 7×5 的矩陣表到 matrix_PO_sur.csv


In [94]:
import numpy as np
import os
import csv

# 不同的 N 值和 dist 值
N_values = [5, 10, 20, 40, 60, 80, 100]
dist_values = [0.6, 0.8, 0.96, 1, 1.2]

# 基礎路徑
base_path_nn_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_nn_20250415\shap"
base_path_xgb_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap"


# 輸出 CSV
output_csv = "matrix_PIO_sur.csv"

# 建立矩陣，第一列是表頭
matrix = [["N值 \\ dist值"] + dist_values]

for N in N_values:
    row = [N]
    for dist in dist_values:
        file_template = f"deploy_decision_survivalrate_average_{N}_set_10_dist_{dist}.npy"
        
        try:
            data_nn = np.load(os.path.join(base_path_nn_shap, file_template), allow_pickle=True)
            avg_nn = np.mean(data_nn)
        except:
            avg_nn = None
        
        try:
            data_xgb = np.load(os.path.join(base_path_xgb_shap, file_template), allow_pickle=True)
            avg_xgb = np.mean(data_xgb)
        except:
            avg_xgb = None
        
        if avg_nn is not None and avg_xgb is not None:
            rel_diff = ((avg_xgb - avg_nn) / avg_nn) * 100
            row.append(f"{rel_diff:+.2f}%")
        else:
            row.append("缺少數據")
    
    matrix.append(row)

# 存成 CSV
with open(output_csv, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerows(matrix)

print(f"\n✅ 已輸出 7×5 的矩陣表到 {output_csv}")



✅ 已輸出 7×5 的矩陣表到 matrix_PIO_sur.csv
