# 讀取檔案

In [64]:
import numpy as np
import os


# 檔案路徑
file_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap\deploy_decision_survivalrate_5_set_10_dist_0.npy"

# 讀取 .npy 檔案
data = np.load(file_path, allow_pickle=True)

# 顯示資料型態與內容
print("資料型態:", type(data))
print("資料形狀:", getattr(data, 'shape', '無 shape 屬性'))
print("內容預覽:\n", data)


資料型態: <class 'numpy.ndarray'>
資料形狀: (10, 1983)
內容預覽:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [65]:
import numpy as np
import os


# 檔案路徑
file_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp\deploy_decision_survivalrate_5_set_10_dist_0.npy"

# 讀取 .npy 檔案
data= np.load(file_path, allow_pickle=True)

# 顯示資料型態與內容
print("資料型態:", type(data))
print("資料形狀:", getattr(data, 'shape', '無 shape 屬性'))
print("內容預覽:\n", data)


資料型態: <class 'numpy.ndarray'>
資料形狀: (10, 1983)
內容預覽:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# random 之資料計算

In [66]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_random_20250822"

# 不同的 coverage 值
coverages = [5, 10, 20, 40, 60, 80, 100]

# 儲存結果
results = {}

print("=" * 60)
for coverage in coverages:
    # 建立檔案名稱
    file_name = f"random_choose_survivalrate_average_{coverage}_set_10.npy"
    file_path = os.path.join(base_path, file_name)
    # 檢查檔案是否存在
    if os.path.exists(file_path):
        # 讀取資料
        data = np.load(file_path, allow_pickle=True)
        
        # 計算平均值
        mean_value = np.mean(data)
        
        # 儲存結果
        results[coverage] = mean_value
        
        # print(f"Coverage {coverage:3d}: 平均值 = {mean_value:.6f}")
        # print(f"  - 資料形狀: {data.shape}")
        # print(f"  - 資料範圍: [{np.min(data):.6f}, {np.max(data):.6f}]")
        # print("-" * 60)
    else:
        print(f"Coverage {coverage:3d}: 檔案不存在！")
        print(f"  - 路徑: {file_path}")
        print("-" * 60)

print("=" * 60)
print("\n摘要:")
print(f"{'N':<12} {'平均值 (%)':<15}")
print("-" * 27)
for coverage, mean_val in results.items():
    print(f"{coverage:<12} {mean_val * 100:<14.2f}%")



摘要:
N            平均值 (%)        
---------------------------
5            1.44          %
10           2.66          %
20           4.97          %
40           8.08          %
60           10.15         %
80           11.56         %
100          12.58         %


## nonzero

In [67]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_random_R+_20251003"

# 不同的 coverage 值
coverages = [5, 10, 20, 40, 60, 80, 100]

# 儲存結果
results = {}

print("=" * 60)
for coverage in coverages:
    # 建立檔案名稱
    file_name = f"random_choose_survivalrate_nonzero_average_{coverage}_set_10.npy"
    file_path = os.path.join(base_path, file_name)
    # 檢查檔案是否存在
    if os.path.exists(file_path):
        # 讀取資料
        data = np.load(file_path, allow_pickle=True)
        
        # 計算平均值
        mean_value = np.mean(data)
        
        # 儲存結果
        results[coverage] = mean_value
        
        # print(f"Coverage {coverage:3d}: 平均值 = {mean_value:.6f}")
        # print(f"  - 資料形狀: {data.shape}")
        # print(f"  - 資料範圍: [{np.min(data):.6f}, {np.max(data):.6f}]")
        # print("-" * 60)
    else:
        print(f"Coverage {coverage:3d}: 檔案不存在！")
        print(f"  - 路徑: {file_path}")
        print("-" * 60)

print("=" * 60)
print("\n摘要:")
print(f"{'N':<12} {'平均值 (%)':<15}")
print("-" * 27)
for coverage, mean_val in results.items():
    print(f"{coverage:<12} {mean_val * 100:<14.2f}%")



摘要:
N            平均值 (%)        
---------------------------
5            18.64         %
10           18.75         %
20           18.82         %
40           19.01         %
60           19.24         %
80           19.41         %
100          19.57         %


# PIO 之資料計算

In [68]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap"

# 不同的 coverage 和 dmin 值
coverages = [5, 10, 20, 40, 60, 80, 100]
dmin_values = [0.6, 0.8, 0.96, 1, 1.2]

# 儲存結果
results = {}

print("=" * 80)
print("開始分析檔案...")
print("=" * 80)

for coverage in coverages:
    results[coverage] = {}
    
    for dmin in dmin_values:
        # 建立檔案名稱 (修正: 使用 coverage 和 dmin 的具體值)
        file_name = f"deploy_decision_survivalrate_average_{coverage}_set_10_dist_{dmin}.npy"
        file_path = os.path.join(base_path, file_name)
        
        # 檢查檔案是否存在
        if os.path.exists(file_path):
            try:
                # 讀取資料
                data = np.load(file_path, allow_pickle=True)
                
                # 計算平均值
                mean_value = np.mean(data)
                
                # 儲存結果
                results[coverage][dmin] = {
                    'mean': mean_value,
                    'shape': data.shape,
                    'min': np.min(data),
                    'max': np.max(data),
                    'std': np.std(data)
                }
                
                # print(f"✓ Coverage {coverage:3d}, Dmin {dmin:.2f}:")
                # print(f"    平均值 = {mean_value:.6f}, 標準差 = {np.std(data):.6f}")
                # print(f"    形狀 = {data.shape}, 範圍 = [{np.min(data):.6f}, {np.max(data):.6f}]")
                
            except Exception as e:
                print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 讀取錯誤 - {e}")
                results[coverage][dmin] = None
        else:
            print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 檔案不存在")
            results[coverage][dmin] = None
    
    # print("-" * 80)

print("=" * 80)
print("\n摘要表格:")
print("=" * 80)

# 建立表格標題
header = f"{'N':<12}"
for dmin in dmin_values:
    header += f"{'Dmin=' + str(dmin):<15}"
print(header)
print("-" * (12 + 15 * len(dmin_values)))

# 輸出表格內容
for coverage in coverages:
    row = f"{coverage:<12}"
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            row += f"{results[coverage][dmin]['mean']:<14.1%}"
        else:
            row += f"{'N/A':<15}"
    print(row)

print("=" * 80)

# 額外統計: 找出最佳組合
print("\n最佳組合 (最大平均值):")
max_mean = -np.inf
best_coverage = None
best_dmin = None

for coverage in coverages:
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            current_mean = results[coverage][dmin]['mean']
            if current_mean > max_mean:
                max_mean = current_mean
                best_coverage = coverage
                best_dmin = dmin

if best_coverage is not None:
    print(f"Coverage = {best_coverage}, Dmin = {best_dmin}, 平均值 = {max_mean:.6f}")
else:
    print("未找到有效數據")

開始分析檔案...

摘要表格:
N           Dmin=0.6       Dmin=0.8       Dmin=0.96      Dmin=1         Dmin=1.2       
---------------------------------------------------------------------------------------
5           2.2%          2.2%          2.2%          2.2%          2.2%          
10          4.1%          4.1%          4.1%          4.1%          4.1%          
20          6.5%          7.0%          7.6%          7.6%          7.7%          
40          9.0%          10.1%         10.6%         10.7%         10.7%         
60          10.7%         11.5%         11.7%         11.9%         12.3%         
80          11.8%         12.1%         12.8%         12.9%         13.6%         
100         12.3%         13.1%         13.6%         13.7%         14.8%         

最佳組合 (最大平均值):
Coverage = 100, Dmin = 1.2, 平均值 = 0.147932


## PIO+ nonzero

In [69]:
import numpy as np
import os
import pandas as pd

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap"

# 要測試的AED設置數量列表
loc_num_list = [5, 10, 20, 40, 60, 80, 100]

# AED之間的距離限制列表
dist_list = [0.6, 0.8, 0.96, 1, 1.2]

# 儲存所有結果
results = []

# 遍歷所有組合
for loc_num in loc_num_list:
    for dist in dist_list:
        # 構建檔案路徑
        file_name = f'deploy_decision_survivalrate_{loc_num}_set_10_dist_{dist}.npy'
        file_path = os.path.join(base_path, file_name)
        
        # 檢查檔案是否存在
        if not os.path.exists(file_path):
            print(f"警告: 檔案不存在 - {file_name}")
            continue
        
        # 讀取 .npy 檔案
        data = np.load(file_path, allow_pickle=True)
        
        # 計算每列非0值的平均
        row_means = []
        for i in range(data.shape[0]):
            row = data[i, :]
            non_zero_values = row[row != 0]
            
            if len(non_zero_values) > 0:
                mean_val = np.mean(non_zero_values) * 100  # 轉換為百分比
            else:
                mean_val = 0
            
            row_means.append(mean_val)
        
        # 儲存結果
        result_dict = {
            'loc_num': loc_num,
            'dist': dist,
            'file_name': file_name
        }
        
        # 將每列的平均加入結果
        for i, mean_val in enumerate(row_means):
            result_dict[f'row_{i}_mean'] = mean_val
        
        # 計算總體統計
        result_dict['overall_mean'] = np.mean(row_means)
        result_dict['overall_std'] = np.std(row_means)
        result_dict['overall_min'] = np.min(row_means)
        result_dict['overall_max'] = np.max(row_means)
        
        results.append(result_dict)
        
        # # 顯示當前檔案的結果
        # print(f"\n檔案: {file_name}")
        # print(f"AED數量: {loc_num}, 距離限制: {dist}")
        # print(f"每列的非零平均救援率 (%):")
        # for i, mean_val in enumerate(row_means):
        #     print(f"  第 {i} 列: {mean_val:.4f}%")
        # print(f"整體平均: {result_dict['overall_mean']:.4f}%")
        # print(f"標準差: {result_dict['overall_std']:.4f}%")
        # print("-" * 60)

# 轉換為 DataFrame 並儲存
df_results = pd.DataFrame(results)

# 顯示整體摘要
print("=" * 80)
print("\n摘要表格:")
print("=" * 80)

# 建立表格標題
header = f"{'N':<12}"
for dist in dist_list:
    header += f"{'Dmin=' + str(dist):<15}"
print(header)
print("-" * (12 + 15 * len(dist_list)))

# 輸出表格內容
for loc_num in loc_num_list:
    row = f"{loc_num:<12}"
    for dist in dist_list:
        # 找到對應的結果
        match = df_results[(df_results['loc_num'] == loc_num) & (df_results['dist'] == dist)]
        if not match.empty:
            mean_val = match.iloc[0]['overall_mean']
            row += f"{mean_val:>13.1f}% "
        else:
            row += f"{'N/A':<15}"
    print(row)

print("=" * 80)

# 額外統計: 找出最佳組合
print("\n最佳組合 (最大平均值):")
max_mean = -np.inf
best_loc_num = None
best_dist = None

for result in results:
    current_mean = result['overall_mean']
    if current_mean > max_mean:
        max_mean = current_mean
        best_loc_num = result['loc_num']
        best_dist = result['dist']

if best_loc_num is not None:
    print(f"N = {best_loc_num}, 距離限制 = {best_dist}, 平均值 = {max_mean:.1f}%")
else:
    print("未找到有效數據")

print("=" * 80)



摘要表格:
N           Dmin=0.6       Dmin=0.8       Dmin=0.96      Dmin=1         Dmin=1.2       
---------------------------------------------------------------------------------------
5                    18.7%          18.7%          18.7%          18.7%          18.7% 
10                   18.6%          18.6%          18.6%          18.6%          18.6% 
20                   18.8%          18.7%          18.7%          18.7%          18.6% 
40                   19.1%          19.1%          19.1%          19.1%          19.0% 
60                   19.4%          19.5%          19.5%          19.5%          19.5% 
80                   19.7%          19.8%          19.8%          19.8%          19.8% 
100                  19.9%          20.1%          20.1%          20.1%          20.0% 

最佳組合 (最大平均值):
N = 100, 距離限制 = 1, 平均值 = 20.1%


# PO

In [70]:
import numpy as np
import os

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp"

# 不同的 coverage 和 dmin 值
coverages = [5, 10, 20, 40, 60, 80, 100]
dmin_values = [0.6, 0.8, 0.96, 1, 1.2]

# 儲存結果
results = {}

print("=" * 80)
print("開始分析檔案...")
print("=" * 80)

for coverage in coverages:
    results[coverage] = {}
    
    for dmin in dmin_values:
        # 建立檔案名稱 (修正: 使用 coverage 和 dmin 的具體值)
        file_name = f"deploy_decision_survivalrate_average_{coverage}_set_10_dist_{dmin}.npy"
        file_path = os.path.join(base_path, file_name)
        
        # 檢查檔案是否存在
        if os.path.exists(file_path):
            try:
                # 讀取資料
                data = np.load(file_path, allow_pickle=True)
                
                # 計算平均值
                mean_value = np.mean(data)
                
                # 儲存結果
                results[coverage][dmin] = {
                    'mean': mean_value,
                    'shape': data.shape,
                    'min': np.min(data),
                    'max': np.max(data),
                    'std': np.std(data)
                }
                
                # print(f"✓ Coverage {coverage:3d}, Dmin {dmin:.2f}:")
                # print(f"    平均值 = {mean_value:.6f}, 標準差 = {np.std(data):.6f}")
                # print(f"    形狀 = {data.shape}, 範圍 = [{np.min(data):.6f}, {np.max(data):.6f}]")
                
            except Exception as e:
                print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 讀取錯誤 - {e}")
                results[coverage][dmin] = None
        else:
            print(f"✗ Coverage {coverage:3d}, Dmin {dmin:.2f}: 檔案不存在")
            results[coverage][dmin] = None
    
    # print("-" * 80)

print("=" * 80)
print("\n摘要表格:")
print("=" * 80)

# 建立表格標題
header = f"{'N':<12}"
for dmin in dmin_values:
    header += f"{'Dmin=' + str(dmin):<15}"
print(header)
print("-" * (12 + 15 * len(dmin_values)))

# 輸出表格內容
for coverage in coverages:
    row = f"{coverage:<12}"
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            row += f"{results[coverage][dmin]['mean']:<14.1%}"
        else:
            row += f"{'N/A':<15}"
    print(row)

print("=" * 80)

# 額外統計: 找出最佳組合
print("\n最佳組合 (最大平均值):")
max_mean = -np.inf
best_coverage = None
best_dmin = None

for coverage in coverages:
    for dmin in dmin_values:
        if results[coverage][dmin] is not None:
            current_mean = results[coverage][dmin]['mean']
            if current_mean > max_mean:
                max_mean = current_mean
                best_coverage = coverage
                best_dmin = dmin

if best_coverage is not None:
    print(f"Coverage = {best_coverage}, Dmin = {best_dmin}, 平均值 = {max_mean:.6f}")
else:
    print("未找到有效數據")

開始分析檔案...

摘要表格:
N           Dmin=0.6       Dmin=0.8       Dmin=0.96      Dmin=1         Dmin=1.2       
---------------------------------------------------------------------------------------
5           1.7%          1.7%          1.9%          1.9%          2.1%          
10          2.3%          2.9%          3.2%          3.2%          3.4%          
20          3.8%          4.6%          5.2%          5.3%          5.7%          
40          5.7%          6.6%          7.5%          7.8%          8.9%          
60          6.8%          8.4%          9.6%          9.8%          10.8%         
80          8.0%          9.8%          10.8%         11.1%         12.3%         
100         9.1%          10.8%         12.0%         12.3%         13.9%         

最佳組合 (最大平均值):
Coverage = 100, Dmin = 1.2, 平均值 = 0.138720


## PO+ nonzero

In [71]:
import numpy as np
import os
import pandas as pd

# 基礎路徑
base_path = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp"

# 要測試的AED設置數量列表
loc_num_list = [5, 10, 20, 40, 60, 80, 100]

# AED之間的距離限制列表
dist_list = [0.6, 0.8, 0.96, 1, 1.2]

# 儲存所有結果
results = []

# 遍歷所有組合
for loc_num in loc_num_list:
    for dist in dist_list:
        # 構建檔案路徑
        file_name = f'deploy_decision_survivalrate_{loc_num}_set_10_dist_{dist}.npy'
        file_path = os.path.join(base_path, file_name)
        
        # 檢查檔案是否存在
        if not os.path.exists(file_path):
            print(f"警告: 檔案不存在 - {file_name}")
            continue
        
        # 讀取 .npy 檔案
        data = np.load(file_path, allow_pickle=True)
        
        # 計算每列非0值的平均
        row_means = []
        for i in range(data.shape[0]):
            row = data[i, :]
            non_zero_values = row[row != 0]
            
            if len(non_zero_values) > 0:
                mean_val = np.mean(non_zero_values) * 100  # 轉換為百分比
            else:
                mean_val = 0
            
            row_means.append(mean_val)
        
        # 儲存結果
        result_dict = {
            'loc_num': loc_num,
            'dist': dist,
            'file_name': file_name
        }
        
        # 將每列的平均加入結果
        for i, mean_val in enumerate(row_means):
            result_dict[f'row_{i}_mean'] = mean_val
        
        # 計算總體統計
        result_dict['overall_mean'] = np.mean(row_means)
        result_dict['overall_std'] = np.std(row_means)
        result_dict['overall_min'] = np.min(row_means)
        result_dict['overall_max'] = np.max(row_means)
        
        results.append(result_dict)
        
        # # 顯示當前檔案的結果
        # print(f"\n檔案: {file_name}")
        # print(f"AED數量: {loc_num}, 距離限制: {dist}")
        # print(f"每列的非零平均救援率 (%):")
        # for i, mean_val in enumerate(row_means):
        #     print(f"  第 {i} 列: {mean_val:.4f}%")
        # print(f"整體平均: {result_dict['overall_mean']:.4f}%")
        # print(f"標準差: {result_dict['overall_std']:.4f}%")
        # print("-" * 60)

# 轉換為 DataFrame 並儲存
df_results = pd.DataFrame(results)

# 顯示整體摘要
print("=" * 80)
print("\n摘要表格:")
print("=" * 80)

# 建立表格標題
header = f"{'N':<12}"
for dist in dist_list:
    header += f"{'Dmin=' + str(dist):<15}"
print(header)
print("-" * (12 + 15 * len(dist_list)))

# 輸出表格內容
for loc_num in loc_num_list:
    row = f"{loc_num:<12}"
    for dist in dist_list:
        # 找到對應的結果
        match = df_results[(df_results['loc_num'] == loc_num) & (df_results['dist'] == dist)]
        if not match.empty:
            mean_val = match.iloc[0]['overall_mean']
            row += f"{mean_val:>13.1f}% "
        else:
            row += f"{'N/A':<15}"
    print(row)

print("=" * 80)

# 額外統計: 找出最佳組合
print("\n最佳組合 (最大平均值):")
max_mean = -np.inf
best_loc_num = None
best_dist = None

for result in results:
    current_mean = result['overall_mean']
    if current_mean > max_mean:
        max_mean = current_mean
        best_loc_num = result['loc_num']
        best_dist = result['dist']

if best_loc_num is not None:
    print(f"N = {best_loc_num}, 距離限制 = {best_dist}, 平均值 = {max_mean:.1f}%")
else:
    print("未找到有效數據")

print("=" * 80)



摘要表格:
N           Dmin=0.6       Dmin=0.8       Dmin=0.96      Dmin=1         Dmin=1.2       
---------------------------------------------------------------------------------------
5                    18.9%          18.9%          18.8%          18.8%          18.8% 
10                   19.0%          18.9%          19.0%          19.0%          18.9% 
20                   19.3%          19.2%          19.2%          19.1%          19.1% 
40                   19.6%          19.7%          19.6%          19.5%          19.5% 
60                   19.9%          19.8%          19.9%          19.9%          19.8% 
80                   20.0%          20.1%          20.1%          20.1%          20.0% 
100                  20.1%          20.3%          20.3%          20.3%          20.2% 

最佳組合 (最大平均值):
N = 100, 距離限制 = 0.8, 平均值 = 20.3%


# suvival rate

In [72]:
import numpy as np
import os
import csv

# 不同的 N 值和 dist 值
N_values = [5, 10, 20, 40, 60, 80, 100]
dist_values = [0.6, 0.8, 0.96, 1, 1.2]

# 基礎路徑
base_path_nn_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_nn_20250415\mlp"
base_path_xgb_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\mlp"


# 輸出 CSV
output_csv = "matrix_PO_sur.csv"

# 建立矩陣，第一列是表頭
matrix = [["N值 \\ dist值"] + dist_values]

for N in N_values:
    row = [N]
    for dist in dist_values:
        file_template = f"deploy_decision_survivalrate_average_{N}_set_10_dist_{dist}.npy"
        
        try:
            data_nn = np.load(os.path.join(base_path_nn_shap, file_template), allow_pickle=True)
            avg_nn = np.mean(data_nn)
        except:
            avg_nn = None
        
        try:
            data_xgb = np.load(os.path.join(base_path_xgb_shap, file_template), allow_pickle=True)
            avg_xgb = np.mean(data_xgb)
        except:
            avg_xgb = None
        
        if avg_nn is not None and avg_xgb is not None:
            rel_diff = ((avg_xgb - avg_nn) / avg_nn) * 100
            row.append(f"{rel_diff:+.2f}%")
        else:
            row.append("缺少數據")
    
    matrix.append(row)

# 存成 CSV
with open(output_csv, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerows(matrix)

print(f"\n✅ 已輸出 7×5 的矩陣表到 {output_csv}")



✅ 已輸出 7×5 的矩陣表到 matrix_PO_sur.csv


In [73]:
import numpy as np
import os
import csv

# 不同的 N 值和 dist 值
N_values = [5, 10, 20, 40, 60, 80, 100]
dist_values = [0.6, 0.8, 0.96, 1, 1.2]

# 基礎路徑
base_path_nn_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_nn_20250415\shap"
base_path_xgb_shap = r"C:\Users\Yuan\Desktop\YUAN\OHCA_TBSI_framwork\python-ML-project-Framework-AED-predict-then-optimize\Optimizor\results_xgb_20250415\shap"


# 輸出 CSV
output_csv = "matrix_PIO_sur.csv"

# 建立矩陣，第一列是表頭
matrix = [["N值 \\ dist值"] + dist_values]

for N in N_values:
    row = [N]
    for dist in dist_values:
        file_template = f"deploy_decision_survivalrate_average_{N}_set_10_dist_{dist}.npy"
        
        try:
            data_nn = np.load(os.path.join(base_path_nn_shap, file_template), allow_pickle=True)
            avg_nn = np.mean(data_nn)
        except:
            avg_nn = None
        
        try:
            data_xgb = np.load(os.path.join(base_path_xgb_shap, file_template), allow_pickle=True)
            avg_xgb = np.mean(data_xgb)
        except:
            avg_xgb = None
        
        if avg_nn is not None and avg_xgb is not None:
            rel_diff = ((avg_xgb - avg_nn) / avg_nn) * 100
            row.append(f"{rel_diff:+.2f}%")
        else:
            row.append("缺少數據")
    
    matrix.append(row)

# 存成 CSV
with open(output_csv, mode="w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerows(matrix)

print(f"\n✅ 已輸出 7×5 的矩陣表到 {output_csv}")



✅ 已輸出 7×5 的矩陣表到 matrix_PIO_sur.csv
